version: "2"
services:
  mariadb:
    image: "bitnami/mariadb:10.3"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpassword
      - MARIADB_DATABASE=dbname
    volumes:
      - "mariadb_data:/bitnami"
  ghost:
    image: "bitnami/ghost:3"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=dbuser
      - GHOST_DATABASE_NAME=dbname
      - GHOST_DATABASE_PASSWORD=dbpassword
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=vayvoncantho.com
      - GHOST_USERNAME=username
      - GHOST_PASSWORD=password
      - GHOST_EMAIL=email@gmail.com
    ports:
      - "80:2368"
    volumes:
      - "ghost_data:/bitnami"
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
